In [36]:
#import packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [37]:
#import data
data = pd.read_csv('spambase.csv',header= None)

In [38]:
#inspect data
data

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,57
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.000,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.010,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.000,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.000,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4596,0.31,0.00,0.62,0.0,0.00,0.31,0.00,0.00,0.00,0.00,...,0.000,0.232,0.0,0.000,0.000,0.000,1.142,3,88,0
4597,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.353,0.000,0.000,1.555,4,14,0
4598,0.30,0.00,0.30,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.102,0.718,0.0,0.000,0.000,0.000,1.404,6,118,0
4599,0.96,0.00,0.00,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.000,0.057,0.0,0.000,0.000,0.000,1.147,5,78,0
4600,0.00,0.00,0.65,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.125,0.000,0.000,1.250,5,40,0

In [39]:
#split the dataset into train set and test set
x_train,x_test , y_train , y_test = train_test_split(data.iloc[:, 0:57],data.iloc[:, 57],test_size = .25)

In [40]:
x_train

,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
465,0.21,0.10,0.52,0.0,1.26,0.10,0.00,0.00,0.42,0.52,...,0.0,0.000,0.028,0.000,0.141,3.305,0.000,11.288,193,1016
1551,0.26,0.05,1.45,0.0,0.37,0.10,0.00,0.00,0.10,0.10,...,0.0,0.000,0.076,0.000,0.262,0.186,0.025,11.793,289,2288
1791,0.10,0.20,1.01,0.0,0.80,0.80,0.50,0.00,0.80,0.10,...,0.0,0.000,0.110,0.000,0.488,0.157,0.015,8.550,669,1351
4031,0.00,0.00,0.00,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.0,0.000,0.094,0.047,0.094,0.000,0.000,1.919,13,167
1742,0.19,0.19,0.29,0.0,1.07,0.19,0.19,0.97,0.87,0.58,...,0.0,0.000,0.000,0.202,0.404,0.233,0.031,4.320,49,877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,0.16,0.00,0.67,0.0,0.33,0.16,0.33,0.84,0.16,0.50,...,0.0,0.000,0.218,0.000,1.118,0.054,0.000,4.928,63,621
1937,0.00,0.00,0.35,0.0,0.35,0.71,0.00,0.00,0.00,0.00,...,0.0,0.000,0.124,0.000,0.372,0.000,0.000,1.641,12,110
450,0.31,0.31,0.31,0.0,0.00,0.00,0.31,0.00,0.31,0.31,...,0.0,0.000,0.750,0.000,0.890,0.046,0.046,12.382,138,421
1836,0.00,0.00,1.88,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.323,0.323,0.000,0.000,0.000,0.000,1.000,1,12
2306,0.00,0.00,0.00,0.0,0.00,0.00,1.78,0.00,0.00,1.78,...,0.0,0.000,0.000,0.000,0.000,0.000,0.000,7.000,35,63

In [41]:
#creat the model using Naive Bayes
model = MultinomialNB()
model.fit(x_train, y_train)

MultinomialNB()

In [42]:
model.score(x_test,y_test)

0.7914856646394439

In [43]:
model.score(x_train,y_train)

0.7915942028985508